### ISSUE TITLE
unsupported port in ingen

### ISSUE THREAD

**Issue by rhetr** [harryhaaren/openAV-Sorcer#10]
i noticed that whenever i run ingen i get this warning:
    Ignoring <http://www.openavproductions.com/sorcer>; unsupported port <midiin>

and it looks like sorcer can't be loaded.

**Comment by harryhaaren** [comment]
Hi @rhetr, 
Could you paste the output of `lv2info http://www.openavproductions.com/sorcer` please?

I guess this error is due to the MIDI "Event" port that Sorcer has used in the past - it currently also has Atom MIDI support since commmit e6e28ba26cfc3047e877ec4e5a30264b4be8037a on Sep 3, 2014.. is there a chance yours is older than this?

The `lv2info` output should inform why Ingen is complaining... so lets start there :)
Cheers, -Harry

**Comment by rhetr** [comment]
I'm using the version packaged with kxstudio... running `dpkg -l sorcer` shows theversion as 1:1.2+git20140320-1kxstudio1 which indeed looks like it's older than https://github.com/harryhaaren/openAV-Sorcer/commit/e6e28ba26cfc3047e877ec4e5a30264b4be8037a... I'll ask falktx to update the package. here's the output of lv2info anyway

    http://www.openavproductions.com/sorcer

	Name:              Sorcer
	Class:             Instrument
	Author:            OpenAV Productions
	Has latency:       no
	Bundle:            file:///usr/lib/lv2/sorcer.lv2/
	Binary:            file:///usr/lib/lv2/sorcer.lv2/sorcer.so
	UIs:
		http://www.openavproductions.com/sorcer/gui
			Class:  http://lv2plug.in/ns/extensions/ui#X11UI
			Binary: file:///usr/lib/lv2/sorcer.lv2/sorcer_ui.so
			Bundle: file:///usr/lib/lv2/sorcer.lv2/
	Data URIs:         file:///usr/lib/lv2/sorcer.lv2/sorcer.ttl
	                   file:///usr/lib/lv2/sorcer.lv2/manifest.ttl
	Optional Features: http://lv2plug.in/ns/extensions/ui#noUserResize
	                   http://lv2plug.in/ns/lv2core#hardRtCapable
	                   http://lv2plug.in/ns/ext/port-props#supportsStrictBounds
	Presets: 
	         sorcerBasicOrgan
	         sorcerChords
	         sorcerBasicBass
	         sorcerBasicBip
	         sorcerBasicWobble

	Port 0:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      attack
		Name:        attack
		Minimum:     0.010000
		Maximum:     1.000000
		Default:     0.010000
		Properties:  http://lv2plug.in/ns/ext/port-props#hasStrictBounds


	Port 1:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      decay
		Name:        decay
		Minimum:     0.000000
		Maximum:     1.000000
		Default:     0.300000
		Properties:  http://lv2plug.in/ns/ext/port-props#hasStrictBounds


	Port 2:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      release
		Name:        release
		Minimum:     0.000000
		Maximum:     1.000000
		Default:     0.200000
		Properties:  http://lv2plug.in/ns/ext/port-props#hasStrictBounds


	Port 3:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      sustain
		Name:        sustain
		Minimum:     0.000000
		Maximum:     1.000000
		Default:     1.000000
		Properties:  http://lv2plug.in/ns/ext/port-props#hasStrictBounds


	Port 4:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      vol
		Name:        vol
		Minimum:     0.000000
		Maximum:     1.000000
		Default:     0.300000
		Properties:  http://lv2plug.in/ns/ext/port-props#hasStrictBounds


	Port 5:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      compAttack
		Name:        compAttack
		Minimum:     0.000000
		Maximum:     1.000000
		Default:     0.000000
		Properties:  http://lv2plug.in/ns/ext/port-props#hasStrictBounds


	Port 6:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      compMakeup
		Name:        compMakeup
		Minimum:     0.000000
		Maximum:     1.000000
		Default:     0.000000
		Properties:  http://lv2plug.in/ns/ext/port-props#hasStrictBounds


	Port 7:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      compRelease
		Name:        compRelease
		Minimum:     0.000000
		Maximum:     1.000000
		Default:     0.000000
		Properties:  http://lv2plug.in/ns/ext/port-props#hasStrictBounds


	Port 8:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      compThreshold
		Name:        compThreshold
		Minimum:     0.000000
		Maximum:     1.000000
		Default:     0.000000
		Properties:  http://lv2plug.in/ns/ext/port-props#hasStrictBounds


	Port 9:
		Type:        http://lv2plug.in/ns/lv2core#InputPort
		             http://lv2plug.in/ns/lv2core#ControlPort
		Symbol:      compressorEnable
		Name:        compressorEnable
		Minimum:     0.000000
		Maximum:     1.000000
		Default:     0.000000
		Properties:  http://lv2plug.in/ns/ext/port-props#hasStrictBounds


	Port 10:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      filter1cutoff
		Name:        filter1cutoff
		Minimum:     0.000000
		Maximum:     1.000000
		Default:     1.000000
		Properties:  http://lv2plug.in/ns/ext/port-props#hasStrictBounds


	Port 11:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      filter1lfo1range
		Name:        filter1lfo1range
		Minimum:     0.000000
		Maximum:     1.000000
		Default:     0.000000
		Properties:  http://lv2plug.in/ns/ext/port-props#hasStrictBounds


	Port 12:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      lfo1_wavetable1pos
		Name:        lfo1_wavetable1pos
		Minimum:     0.000000
		Maximum:     1.000000
		Default:     0.000000
		Properties:  http://lv2plug.in/ns/ext/port-props#hasStrictBounds


	Port 13:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      lfo1_wavetable2pos
		Name:        lfo1_wavetable2pos
		Minimum:     0.000000
		Maximum:     1.000000
		Default:     0.000000
		Properties:  http://lv2plug.in/ns/ext/port-props#hasStrictBounds


	Port 14:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      lfo1amp
		Name:        lfo1amp
		Minimum:     0.000000
		Maximum:     1.000000
		Default:     0.100000
		Properties:  http://lv2plug.in/ns/ext/port-props#hasStrictBounds


	Port 15:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      lfo1freq
		Name:        lfo1freq
		Minimum:     0.000000
		Maximum:     1.000000
		Default:     0.300000
		Properties:  http://lv2plug.in/ns/ext/port-props#hasStrictBounds


	Port 16:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      osc1vol
		Name:        osc1vol
		Minimum:     0.000000
		Maximum:     1.000000
		Default:     0.300000
		Properties:  http://lv2plug.in/ns/ext/port-props#hasStrictBounds


	Port 17:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      osc2vol
		Name:        osc2vol
		Minimum:     0.000000
		Maximum:     1.000000
		Default:     0.300000
		Properties:  http://lv2plug.in/ns/ext/port-props#hasStrictBounds


	Port 18:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      osc3vol
		Name:        osc3vol
		Minimum:     0.000000
		Maximum:     1.000000
		Default:     0.300000
		Properties:  http://lv2plug.in/ns/ext/port-props#hasStrictBounds


	Port 19:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#OutputPort
		Symbol:      output_db
		Name:        output_db
		Minimum:     -96.000000
		Maximum:     10.000000
		Default:     -96.000000

	Port 20:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      wavetable1pos
		Name:        wavetable1pos
		Minimum:     0.000000
		Maximum:     1.000000
		Default:     0.000000
		Properties:  http://lv2plug.in/ns/ext/port-props#hasStrictBounds


	Port 21:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      wavetable2pos
		Name:        wavetable2pos
		Minimum:     0.000000
		Maximum:     1.000000
		Default:     0.000000
		Properties:  http://lv2plug.in/ns/ext/port-props#hasStrictBounds


	Port 22:
		Type:        http://lv2plug.in/ns/lv2core#AudioPort
		             http://lv2plug.in/ns/lv2core#OutputPort
		Symbol:      out0
		Name:        out0

	Port 23:
		Type:        http://lv2plug.in/ns/ext/event#EventPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Supported events:
			http://lv2plug.in/ns/ext/midi#MidiEvent

		Symbol:      midiin
		Name:        midiin

	Port 24:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      nvoices
		Name:        Polyphony
		Minimum:     1.000000
		Maximum:     16.000000
		Default:     8.000000
		Properties:  http://lv2plug.in/ns/lv2core#integer
		             http://lv2plug.in/ns/ext/port-props#hasStrictBounds

**Comment by falkTX** [comment]
I was waiting for a new release before pushing an update.
Is the latest git version stable to use?
