### ISSUE TITLE
1.1.2 release can't be built

### ISSUE THREAD

**Issue by falkTX** [harryhaaren/openAV-Sorcer#11]
I just grabbed the 1.1.2 release you made, trying to build it I get the following error:
```
/«PKGBUILDDIR»/gui/avtk.h:22:27: fatal error: avtk/avtk_box.h: No such file or directory
```
And it's correct, avtk_box.h doesn't exist anywhere.

Did you forget to add those files?

**Comment by falkTX** [comment]
I found the file at this url:
https://raw.githubusercontent.com/harryhaaren/openAV-Luppp/master/src/avtk/avtk_box.h

And sorcer now seems to build.

I had to make a small change, line 42 became this:
```
label = _label ? strdup(_label) : NULL;
```
otherwise the UI would crash on close (you can't call strdup on null char arrays).

**Comment by harryhaaren** [comment]
Yes i left out Avtk_Box from the commmit - now fixed in 9da6481cb609cd3aa7a9c988fab2f66571c2b04b. I'm surprised the Luppp avtk_box works, but this one is better. 

If it compiles / works fine, I can do a 1.1.3 release.

**Comment by falkTX** [comment]
seems to work fine with that new file.
but I haven't tested extensively.

**Comment by harryhaaren** [comment]
This should have been closed after comment https://github.com/harryhaaren/openAV-Sorcer/issues/11#issuecomment-109942643. Closing now
