### ISSUE TITLE
Package 'ntk' not found

### ISSUE THREAD

**Issue by EwonRael** [harryhaaren/openAV-Sorcer#12]
When I try and install it says that package 'ntk' not found. 
CMake Error at /usr/share/cmake-3.2/Modules/FindPkgConfig.cmake:344 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.2/Modules/FindPkgConfig.cmake:506 (_pkg_check_modules_internal)
  CMakeLists.txt:21 (pkg_check_modules)

-- Configuring incomplete, errors occurred!

**Comment by harryhaaren** [comment]
Hi @EwonRael,

You'll need to install NTK, which is not usually packaged by distors:
```
git clone git://git.tuxfamily.org/gitroot/non/fltk.git ntk
cd ntk
./waf configure --prefix=/usr
./waf
./waf install
```

That will install NTK where your OS will pickup the package automatically.

This should be documented in the Sorcer build instructions - I'll update that now.
Cheers, -Harry

**Comment by EwonRael** [comment]
fantastically fast response! You are the man!

**Comment by rotchotcho** [comment]
With that installation of NTK you need to run 
`export PKG_CONFIG_PATH=/usr/lib64/pkgconfig/`
else ntk is still not founded

**Comment by peterlongfield** [comment]
At the last setp I have all red :
`PermissionError: [Errno 13] Permission denied: 'libntk.a.1.3.1000' -> '/usr/lib/libntk.a.1'  `
:(

**Comment by WMRamadan** [comment]
Very poor installation instructions in my opinion. The above repo mentioned by @harryhaaren no longer exists.

Using "meson build" gives the following error:

Run-time dependency ntk found: NO (tried pkgconfig and cmake)

meson.build:37:2: ERROR: Dependency "ntk" not found, tried pkgconfig and cmake

Using "cmake" gives the following error:
-- Architecture:  x86_64
-- Checking for module 'ntk'
--   No package 'ntk' found

**Comment by harryhaaren** [comment]
Hi WMRamadan, thanks for reporting the build issues, please note my above comments are from 2016 (and yes it has become outdated). You've found install instructions here already; https://github.com/openAVproductions/openAV-Luppp/issues/319 the same NTK is required here.

As this issue is from 2016 I'll lock this, please open a new issue for if required.
